on:
  push:
jobs:
  job1:
    name: "Hello World"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - run: ls


      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: path/to/artifact/world.txt

  job2:
    name: "download artifact"
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Display structure of downloaded files
        run: ls -R

  job3:
    name: "ls"
    runs-on: ubuntu-latest
    steps:
      - run: ls



